version: '3.7'

services:
  metabase:
    container_name: metabase
    image: metabase/metabase
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/metabase-data
    environment: 
      - "MB_DB_FILE=/metabase-data/metabase.db"
