version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-management
    networks: 
      - app
    restart: always
    ports:
      - "5672:5672"
    environment: 
      - "RABBITMQ_DEFAULT_USER=rabbit"
      - "RABBITMQ_DEFAULT_PASS=rabbitmq"
    volumes:
      - data:/var/lib/rabbitmq
networks: 
  app:
    external: true
volumes:
  data:
