version: "3.7"
services:
  ci:
    image: portainer/portainer
    restart: always
    container_name: "portainer"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

volumes:
  data:
