version: '3.7'

services:
  redis:
    container_name: redis
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - "36379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - data:/data

volumes:
  data:
